version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/website:/home/paul/website
      - ./data/users:/etc/apache2
      - /home/paul/website/files:/home/paul/website/files
      - /home/paul/website/repkalinux.deb:/home/paul/website/repkalinux.deb
      - /home/paul/website/rep2phone:/home/paul/website/rep2phone
      - /home/paul/website/burger:/home/paul/website/burger
      - /home/paul/website/repgame:/home/paul/website/repgame
      - /home/paul/website/repcube:/home/paul/website/repcube
    command: "/bin/sh -c 'while true; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while true; do certbot renew; sleep 12h & wait $${!}; done;'"
